# Rotation of Axis Labels

The `angle` parameter in `elementText()` function allows to rotate the text. 

Note: currently this only works for axis labels, i.e. for `axisText, axisTextX, axisTextY` parameters in `theme()`.

1. [Default Axis Labels Layout](#1.-Default-Axis-Labels-Layout)  

2. [Layout Labels for Discrete Axis](#2.-Layout-Labels-for-Discrete-Axis)  
 
3. [Layout Labels for Continuous Axis](#3.-Layout-Labels-for-Continuous-Axis)

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.10.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.6.1.

In [3]:
val df = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/midwest.csv")
df.head()

untitled,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,popother,percwhite,percblack,percamerindan,percasian,percother,popadults,perchsd,percollege,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category
1,561,ADAMS,IL,0.052000,66090,1270.961540,63917,1702,98,249,124,96.712059,2.575276,0.148283,0.376759,0.187623,43298,75.107395,19.631392,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR
2,562,ALEXANDER,IL,0.014000,10626,759.000000,7054,3496,19,48,9,66.384340,32.900433,0.178807,0.451722,0.084698,6724,59.726353,11.243308,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR
3,563,BOND,IL,0.022000,14991,681.409091,14477,429,35,16,34,96.571276,2.861717,0.233473,0.106731,0.226803,9669,69.334988,17.033819,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR
4,564,BOONE,IL,0.017000,30806,1812.117650,29344,127,46,150,1139,95.254171,0.412257,0.149322,0.486918,3.697332,19272,75.472188,17.278954,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU
5,565,BROWN,IL,0.018000,5836,324.222222,5264,547,14,5,6,90.198766,9.372858,0.239890,0.085675,0.102810,3979,68.861523,14.475999,3.367680,4815,82.505141,13.520249,13.022889,11.143211,19.200000,0,AAR

In [4]:
val fullStateNames = mapOf(
    "IL" to "Illinois",
    "IN" to "Indiana",
    "MI" to "Michigan",
    "OH" to "Ohio",
    "WI" to "Wisconsin"
)

val data = df.toMap().mapValues { (key, values) ->
    if (key == "state") {
        values.map { value -> fullStateNames[value] ?: value }
    } else {
        values
    }
}

In [5]:
val highlightAxisLabels = theme(
    text=elementText(color="gray", size=13), 
    axisText=elementText(color="blue")
)

#### 1. Default Axis Labels Layout

In [6]:
val p = letsPlot(data) + geomJitter(color = "light_gray", seed = 42) { x = "state"; y = "poptotal" }
p

#### 2. Layout Labels for Discrete Axis

Let's change rotation angle to check placement of labels on a discrete axis. Labels on y-axis are removed for this demo.

##### 2.1. Horizontal Axis

In [7]:
val xBothPlot = p + theme(axisTextY=elementBlank()) + scaleXDiscrete(position="both")

gggrid(
    plots = listOf(
        xBothPlot + theme(axisText=elementText(angle=10)) + highlightAxisLabels + ggtitle("10°"),
        xBothPlot + theme(axisText=elementText(angle=90)) + highlightAxisLabels + ggtitle("90°")
    ), 
    ncol = 2, 
)

##### 2.2. Vertical Axis

When the rotation angle is set to 90°, some labels are not displayed to avoid overlapping.

In [8]:
gggrid(
    plots = listOf(
        xBothPlot + coordFlip() + theme(axisText=elementText(angle=10)) + highlightAxisLabels + ggtitle("10°"),
        xBothPlot + coordFlip() + theme(axisText=elementText(angle=90)) + highlightAxisLabels + ggtitle("90°")
    ), 
    ncol = 2, 
) + ggsize(1000, 300)

#### 3. Layout Labels for Continuous Axis

For continuous axis the number of labels varies depending on how many it can fit.

##### 3.1. Horizontal Axis

Changing the angle of rotation changes the number of labels on the axis:
90° rotation allows to place more labels on the horizontal axis.

In [9]:
val yBothPlot = p + theme(exponentFormat = listOf("e", -8, 8), axisTextX = elementBlank()) + scaleYContinuous(position="both")

gggrid(
    plots = listOf(
        yBothPlot + coordFlip() + theme(axisText=elementText(angle=10)) + highlightAxisLabels + ggtitle("10°"),
        yBothPlot + coordFlip() + theme(axisText=elementText(angle=90)) + highlightAxisLabels + ggtitle("90°")
    ), 
    ncol = 2, 
)

##### 3.2. Vertical Axis

By changing the angle of rotation, thereby increasing the label heights, we get a reduction in the total number of labels on the vertical axis.

In [10]:
gggrid(
    plots = listOf(
        yBothPlot + theme(axisText=elementText(angle=10)) + highlightAxisLabels + ggtitle("10°"),
        yBothPlot + theme(axisText=elementText(angle=90)) + highlightAxisLabels + ggtitle("90°")
    ), 
    ncol = 2, 
)