# Handling an overplotting on a scatter plot: `geomCount()`/`statSum()`

The `geomCount()`/`statSum()` counts the number of observations at each location. 

Computed variables:

- `..n..` - number of observations at location
- `..prop..` - value in range 0..1 : share of observations at location
- `..proppct..` - value in range 0..100 : % of observations at location

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.13.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.9.0.
Outputs: Web (HTML+JS), Kotlin Notebook (Swing), Static SVG (hidden)

In [3]:
val mpgDf = DataFrame.readCSV ("https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/mpg.csv")
mpgDf.head(3)

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact

In [4]:
val p = letsPlot(mpgDf.toMap()) { x = asDiscrete("class", order=1); y = asDiscrete("drv", order=1) }

#### 1. Plot an Observation Count by Location

In [5]:
p + geomCount()

#### 2. Plot an Observations Share by Location

In [6]:
p + geomCount() { size = "..prop.." }

#### 3. Plot an Observations Share by Drivetrain Type within each Vehicle "class"

Note: group by "class".

In [7]:
p + geomCount() { size = "..prop.."; group="class" }