# Stackable Position Adjustments

## Table of Contents

1. [Stacking in Area Plots ](#default)

2. [Stacking Order](#order)

3. [Other Geometries](#other-geoms)

4. [Parameter `vjust`](#vjust)

5. [Parameter `mode`](#mode)

6. [Negative Values](#negative)

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.10.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.6.1.

In [3]:
val mpgDf = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
mpgDf.head()

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,"1,800000",1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,"1,800000",1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,"2,000000",2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,"2,000000",2008,4,auto(av),f,21,30,p,compact
5,audi,a4,"2,800000",1999,6,auto(l5),f,16,26,p,compact

In [4]:
val mpgData = mpgDf.toMap()

In [5]:
val pairedPalette = scaleBrewer(listOf("color", "fill"), palette = "Paired", format = "d")

<a id="default"></a>

#### 1. Stacking in Area Plots 

Stacking is the default behaviour for most area plots.

"Fill" makes it easier to compare proportions.

In [6]:
letsPlot(mpgData) { x = "drv"; fill = asDiscrete("year") } +
    geomBar() + 
    pairedPalette +
    ggtitle("bar: position='stack' (default)")

In [7]:
letsPlot(mpgData) { x = "drv"; fill = asDiscrete("year") } +
    geomBar(position = positionFill()) + 
    pairedPalette +
    ggtitle("bar: position='fill'")

In [8]:
letsPlot(mpgData) { x = "hwy"; fill = asDiscrete("year") } +
    geomHistogram(bins = 12) +
    pairedPalette +
    ggtitle("histogram: position='stack' (default)")

In [9]:
letsPlot(mpgData) { x = "hwy"; fill = asDiscrete("year") } +
    geomHistogram(bins = 12, position = positionFill()) +
    pairedPalette +
    ggtitle("histogram: position='fill'")

In [10]:
letsPlot(mpgData) { x = "hwy"; fill = asDiscrete("year") } +
    geomArea(stat = Stat.density(), color = "white") +
    pairedPalette +
    ggtitle("area: position='stack' (default)")

In [11]:
letsPlot(mpgData) { x = "hwy"; fill = asDiscrete("year") } +
    geomArea(stat = Stat.density(), position = positionFill(), color = "white") +
    pairedPalette +
    ggtitle("area: position='fill'")

<a id="order"></a>

#### 2. Stacking Order

Control the stacking order by changing the `order` parameter of the `asDiscrete()` function.

In [12]:
letsPlot(mpgData) { x = "hwy" } +
    geomArea(stat = Stat.density(), color = "white") { fill = asDiscrete("drv") } +
    pairedPalette +
    ggtitle("Default order of drive types")

In [13]:
letsPlot(mpgData) { x = "hwy" } +
    geomArea(stat = Stat.density(), color = "white") { fill = asDiscrete("drv", order = -1) } +
    pairedPalette +
    ggtitle("Backward order of drive types")

<a id="other-geoms"></a>

#### 3. Other Geometries

Let's have a look at the geometries, for which the default position adjustment differs from `'stack'` and `'fill'`.

When stacking across multiple layers it's a good idea to set the **`group`** aesthetic - this ensures that all layers are stacked in the same way.

In [14]:
letsPlot(mpgData) { x = "drv"; color = asDiscrete("year") } +
    geomLine(stat = Stat.count(), position = positionStack(), size = 1.5) +
    geomPoint(stat = Stat.count(), position = positionStack(), size = 5) +
    pairedPalette +
    ggtitle("Line and point")

In [15]:
letsPlot(mpgData) { x = "drv" } +
    geomArea(stat = Stat.count(), position = positionStack(), color = "white") { fill = asDiscrete("year") } +
    geomLine(stat = Stat.count(), position = positionStack(), color = "white") { group = "year" } +
    pairedPalette +
    ggtitle("Area and line")

<a id="vjust"></a>

#### 4. Parameter `vjust`

The `vjust` argument of `positionStack()` is used to move the location of plot elements vertically (vjust stands for vertical adjustment).

In [16]:
letsPlot(mpgData) { x = "drv" } +
    geomArea(stat = Stat.count(), position = positionStack(), color = "white") { fill = asDiscrete("year") } +
    geomLabel(stat = Stat.count(), position = positionStack(), color = "black") {
        label = "..count.."; group = "year" 
    } +
    pairedPalette +
    ggtitle("vjust=1 (default)")

In [17]:
letsPlot(mpgData) { x = "drv" } +
    geomArea(stat = Stat.count(), position = positionStack(), color = "white") { fill = asDiscrete("year") } +
    geomLabel(stat = Stat.count(), position = positionStack(vjust = 0.5), color = "black") {
        label = "..count.."; group = "year" 
    } +
    pairedPalette +
    ggtitle("vjust=0.5")

<a id="mode"></a>

#### 5. Parameter `mode`

By default only objects from different groups are stacked over each other, and objects inside one group are positioned as in `position = positionIdentity`.

This behaviour could be changed by switching `mode` parameter.

`mode="all"` means, that each object will be shifted.

In [18]:
letsPlot(mpgData) { x = "hwy"; color = "class" } +
    geomPoint(y = 1, position = positionStack()) +
    coordFixed() + ylim(1 to 35) +
    ggtitle("mode='groups' (default)")

In [19]:
letsPlot(mpgData) { x = "hwy"; color = "class" } +
    geomPoint(y = 1, position = positionStack(mode = "all")) +
    coordFixed() + ylim(1 to 35) +
    ggtitle("mode='all'")

<a id="negative"></a>

#### 6. Negative Values

Stacking supports positive and negative shifts of the objects separately.

In [20]:
val data = mapOf(
    "x" to listOf(0, 1, 2, 0, 1, 2),
    "y" to listOf(4, 2, 3, 0, 1, -1),
    "g" to listOf("a", "a", "a", "b", "b", "b")
)

In [21]:
letsPlot(data) { x = "x"; y = "y"; fill = "g" } +
    geomBar(stat = Stat.identity) +
    geomHLine(yintercept = 0, color = "black") +
    pairedPalette +
    theme(axisLine = "blank", axisTicks = "blank")

In [22]:
letsPlot(data) { x = "x"; y = "y" } +
    geomBar(stat = Stat.identity, position = positionFill()) { fill = "g"} +
    geomLabel(stat = Stat.identity, position = positionFill(vjust = 0.5)) { label = "g"; group = "g" } +
    geomHLine(yintercept=0, color="black") +
    pairedPalette +
    theme(axisLine = "blank", axisTicks = "blank")