# `statSummary()`

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.13.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.9.0.
Outputs: Web (HTML+JS), Kotlin Notebook (Swing), Static SVG (hidden)

In [3]:
var mpgDf = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
val mpgData = mpgDf.toMap()
mpgDf.head()

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.000000,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.800000,1999,6,auto(l5),f,16,26,p,compact

In [4]:
letsPlot(mpgData) { x = "drv"; y = "hwy" } + statSummary()

#### 1. The `geom` Parameter

In [5]:
letsPlot(mpgData) { x = "drv"; y = "hwy" } + statSummary(geom = Geom.crossbar())

#### 2. The `fn` Parameter

In [6]:
letsPlot(mpgData) { x = "drv"; y = "hwy" } + statSummary(geom = Geom.bar(), fn = "count")

#### 3. The `quantiles` Parameter

In [7]:
letsPlot(mpgData) { x = "drv"; y = "hwy" } +
    statSummary(fn = "mq", fnMin = "lq", fnMax = "uq", quantiles = listOf(0.45, 0.5, 0.55))