# New variables computed by `'count'` and  `'count2d'` statistics

`geomBar()` uses `'count'` statistical transformation. In addition to `'..count..'` variable, the statistics now provide additional variables related to sum (`'..sum..'`), `'..prop..'` (proportion) and `'..proppct..'` (proportion in percent).

`geomPie()` uses `'count2d'` statistical transformation. It allows to make a slice sizes proportional to the number of cases in each group (or if the weight aesthetic is supplied, the sum of the weights). Also `'count2d'` provides variables for proportion (`'..prop..'`) and proportion in percent (`'..proppct..'`).

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.13.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.9.0.
Outputs: Web (HTML+JS), Kotlin Notebook (Swing), Static SVG (hidden)

### 1. Data preparation

In [3]:
var mpgDf = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-kotlin/master/docs/examples/data/mpg.csv")
mpgDf.head()

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact
4,audi,a4,2.000000,2008,4,auto(av),f,21,30,p,compact
5,audi,a4,2.800000,1999,6,auto(l5),f,16,26,p,compact

In [4]:
val mpgData = mpgDf.toMap()

In [5]:
val blankTheme = theme(line = elementBlank(), axis = elementBlank())

Prepare the tooltips content to show the variables calculated by the statistics

In [6]:
val tooltipContent = layerTooltips()
                        .title("^fill")
                        .line("count of records in group|@{..count..} (@{..prop..})")
                        .line("total count of records|@{..sum..}")
                        .format("..prop..", ".0%")
                        .format("..count..", ".1f")
                        .format("..sum..", ".1f")

### 2. Default presentation

Let's show the variables computed by the in the tooltips.

In [7]:
ggplot(mpgData) +
    geomBar(tooltips = tooltipContent) { x = "manufacturer"; fill = "class" }

Let's build a pie chart where the sector will correspond to the car class.
All statistical information is shown in tooltips.

In [8]:
ggplot(mpgData) +
    geomPie(size=24, hole=0.2, stroke=1.0, tooltips = tooltipContent) { fill = "class" } +
    blankTheme

### 3. Compute weighted sum

Compute weighted sum instead of simple count: let's use total engine displacement of each class.

In [9]:
ggplot(mpgData) +
    geomPie(size=24, hole=0.2, stroke=1.0, tooltips = tooltipContent) { 
        fill = "class"
        weight = "displ"
    } +
    blankTheme

Then let's order sectors by `'..count..'`:

In [10]:
ggplot(mpgData) +
    geomPie(size=24, hole=0.2, stroke=1.0, tooltips = tooltipContent) { 
        fill = asDiscrete("class", orderBy = "..count..")
        weight = "displ"
    } +
    blankTheme

Map `size` to computed variable `'..sum..'`:

In [11]:
ggplot(mpgData) +
    geomPie(tooltips = tooltipContent) { fill = "class"; size = "..sum.." } +
    facetWrap(facets = "manufacturer", ncol = 5, order = 1) +
    scaleSize(range = 4 to 10) +
    guides(size = "none") +
    blankTheme