# `themeVoid()`


`themeVoid()` is a function to create a plot with a completely blank (or "void") background. 
It removes all elements from the plot, leaving the geometry only.

In [1]:
%useLatestDescriptors
%use dataframe
%use lets-plot

In [2]:
LetsPlot.getInfo()

Lets-Plot Kotlin API v.4.13.0. Frontend: Notebook with dynamically loaded JS. Lets-Plot JS v.4.9.0.
Outputs: Web (HTML+JS), Kotlin Notebook (Swing), Static SVG (hidden)

In [3]:
val mpg = DataFrame.readCSV("https://raw.githubusercontent.com/JetBrains/lets-plot-docs/master/data/mpg.csv")
mpg.head(3)

untitled,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
1,audi,a4,1.800000,1999,4,auto(l5),f,18,29,p,compact
2,audi,a4,1.800000,1999,4,manual(m5),f,21,29,p,compact
3,audi,a4,2.000000,2008,4,manual(m6),f,20,31,p,compact

In [4]:
val p = letsPlot(mpg.toMap()) + geomPie() {  fill = "class"; weight = "displ" }
p

Apply `themeVoid()`:

In [5]:
p + themeVoid()

Faceted plot:

In [6]:
p + facetGrid(x = "year", xFormat = "d") + themeVoid()